[Main]

; Input Data and Information
;COMP_BED_FILE = /home/blackpianocat/Data/Trios/HiChIP/HiChIP_Subcompartments/calder_subc_50k/dsGM19238_30.hic/sub_compartments/all_sub_compartments.bed
INTERACTION_FILE = /home/blackpianocat/Data/Trios/HiChIP/HiChIP_Peaks/dsGM19238_peaks_with_motifs.narrowPeak
;LEF_TRACK_FILE = /home/skorsak/Data/method_paper_data/ENCSR184YZV_CTCF_ChIAPET/ENCFF347QOE_signal_.bigWig
REGION_START = 75000000
REGION_END   = 95000000
CHROM = chr1
PLATFORM = OpenCL
OUT_PATH = test

; Simulation Parameters
N_BEADS = 1000
N_STEPS = 1000000
MC_STEP = 400
BURNIN = 1000
T_INIT = 1.8
T_FINAL =  1.0
METHOD = Annealing
SMOOTHING_INPUT = True
;BETWEEN_FAMILIES_PENALTY = False
DETECT_KNOTS = False

; Stochastic model parameters
EPI_COEFF=1.0
FOLDING_COEFF = 1.0
BIND_COEFF = 1.0
DATA_LOSS_MODE = 0
CONTRASTIVE_BINDING = True
VARIABLE_SLIDING_STEP = False

; Molecular Dynamics
INITIAL_STRUCTURE_TYPE = rw
TOLERANCE = 1.0
DO_COMPARTMENTS = False
;EV_P=0.01
