[Main]

; Input Data and Information
COMP_BED_FILE = /home/blackpianocat/Data/Trios/HiChIP/HiChIP_Subcompartments/calder_subc_50k/dsGM19238_30.hic/sub_compartments/all_sub_compartments.bed
BEDPE_PATH = /home/blackpianocat/Data/method_paper_data/ENCSR184YZV_CTCF_ChIAPET/LHG0052H_loops_cleaned_th10_2.bedpe
;LEF_TRACK_FILE = /home/skorsak/Data/method_paper_data/ENCSR184YZV_CTCF_ChIAPET/ENCFF347QOE_signal_.bigWig
REGION_START = 167000000
REGION_END = 169000000
CHROM = chr1
PLATFORM = OpenCL
OUT_PATH = test

; Simulation Parameters
N_BEADS = 1000
N_STEPS = 100000
MC_STEP = 400
BURNIN = 1000
T_INIT = 2.0
T_FINAL =  1.0
METHOD = Annealing
;BETWEEN_FAMILIES_PENALTY = False
DETECT_KNOTS = False

; Stochastic model parameters
EPI_COEFF=1.0
FOLDING_COEFF = 1.0
BIND_COEFF = 1.0
DATA_LOSS_MODE = 1

; Molecular Dynamics
INITIAL_STRUCTURE_TYPE = rw
SIMULATION_TYPE = MD 
TOLERANCE = 1.0
DO_COMPARTMENTS = False
;EV_P=0.01
